language: r
dist: bionic
latex: false
cache:
  packages: true
  directories:
  - "$HOME/bin"
  - "$HOME/.local/share/fonts"
  - "$HOME/.TinyTex"
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
  - "$HOME/.local/share/renv"
  - "$TRAVIS_BUILD_DIR/renv/library"
addons:
  ssh_known_hosts:
    secure: Q5Xwj3JFmy6MaIxTu4hzExXauJpB9KeNL071PhQm2FRH3iQHrbLvOLuv5XXXyhn7iD0Tu1RsJTaYi5yraGTL8Wvt6GOp+PkX5YXgDjB5do78xMPznxzDJAUs1olhDTbL4G2xvw5P/WN5MO97JdhWJCszXNWCMfigKP33lFwzcHpxI/KVSmfYVDhngEI48V8SMQ1aBwXVTu0ptKk1DI2ePs2PerEBZWF8GTmWTIk/hSSIQrpWPvqd6XSc7wEe4aRSO/f2XuGSqrYRUDYDjYvd/sx+il/CxIF3Y27CvfZZSoV2figII4ffnRCo8WSRMqXCxzVwHLobnZz/v+ePjz5/v17E1NNDRXyF1sRRK5aXIjnXTRDqEMInlgxuyXu6xoVat1ZMmGsdw8Mp+nRRqlXePfXz6yotl6DXxpO3Dr1PeZ6Y6pS/cUzNex1LxPPlehJ/WmwguMwoYgmQDfO7/LAeC6k7zar5JqS3GW1KEUgw3l3eKkVoGBiTYkGvx43Z1HyZLNT9NHiCdtkxi2CD/QZ/jhHG5qsfvjRLM2lZrOAmF1oTzl4d5nG68ky5jk5Bw60+tyoSnVT64rNnnZdlRk9bTd4xaNC0XfstN2qOCaJx5NtMvyQlImsg3SC6AJraBjk0aFlONgeHiP8TNMtPfFusNtjNrfGDTLiFVe2Q0DcWiUQ=
  apt:
    packages:
    - fonts-roboto
    - fonts-oflb-asana-math
before_install:
- Rscript -e "renv::restore()"
- |
  # 1. Install TinyTex manually if not already in cache
  # Travis creates $HOME/.TinyTex if nonexistent, so we check bin subdir
  if [ ! -d $HOME/.TinyTex/texmf-dist ]; then
    Rscript -e "tinytex::install_tinytex()"
  fi
- mkdir -p $HOME/.local/share/fonts
- |
  if [ ! -e $HOME/.local/share/fonts/fira.zip ]; then
    wget https://github.com/bBoxType/FiraSans/archive/master.zip -O $HOME/.local/share/fonts/fira.zip
    unzip $HOME/.local/share/fonts/fira.zip '*.ttf' -d $HOME/.local/share/fonts/fira
  fi
- "$TRAVIS_BUILD_DIR/bin/get_adobe_fonts.sh"
- |
  # Copy fontconfig for possibly maybe xelatex font issue with spaces in font names
  cp $HOME/.TinyTeX/texmf-var/fonts/conf/texlive-fontconfig.conf ~/.fonts.conf
- |
  # 4. Update font cache for previously installed fonts (+ list fonts for debugging)
  fc-cache -fv
  fc-list
before_script:
- '[ -x "$HOME/bin/phantomjs" ] || Rscript -e "webshot::install_phantomjs()"'
script:
- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
before_deploy:
- openssl aes-256-cbc -K $encrypted_09336ea29ba0_key -iv $encrypted_09336ea29ba0_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: pages
  local_dir: _book
  skip_cleanup: true
  keep_history: true
  github_token: "$GITHUB_PAT"
  target_branch: gh-pages
- provider: script
  skip_cleanup: true
  script: rsync -r --quiet $TRAVIS_BUILD_DIR/_book/ -e 'ssh -p 54321' travis@pearson.tadaa-data.de:/srv/bookdown-debug
  on:
    branch: master
notifications:
  email:
    on_success: change
    on_failure: change
