# Methods

## Plotting

With FONTS!

```{r plotting-1, fig.cap="A plot."}
library(ggplot2)

p <- ggplot(iris, aes(x = Species, y = Sepal.Length, color = Species, fill = Species)) +
   geom_boxplot(alpha = .75, show.legend = FALSE) +
   scale_color_brewer(palette = "Dark2", aesthetics = c("color", "fill"))

p + theme_minimal()
```



## Math

Using one dollar sign: $\beta = (X^T X)^{-1} X^T Y$  

Display style with two dollar signs:

$$\beta = (X^T X)^{-1} X^T Y$$

## Using environments

\begin{align}
\mathbb{E}( \widehat{\boldsymbol{\beta}}) 
&= \mathbb{E}\left( \left(\boldsymbol{X}^T \boldsymbol{X}\right)^{-1} \boldsymbol{X}^T \boldsymbol{Y} \right) \\
&= \mathbb{E}\left( \left(\boldsymbol{X}^T \boldsymbol{X}\right)^{-1} \boldsymbol{X}^T \left(\boldsymbol{X} \boldsymbol{\beta}+ \varepsilon \right) \right) \\
&= \mathbb{E}\left( 
   \left(\boldsymbol{X}^T \boldsymbol{X}\right)^{-1} \boldsymbol{X}^T \boldsymbol{X} \boldsymbol{\beta} 
 + \left(\boldsymbol{X}^T \boldsymbol{X}\right)^{-1} \boldsymbol{X}^T \boldsymbol{\varepsilon}
   \right) \\
&= \underbrace{\left(\boldsymbol{X}^T \boldsymbol{X}\right)^{-1} \boldsymbol{X}^T \boldsymbol{X}}_{=\ \boldsymbol{I}} \boldsymbol{\beta} 
 + \underbrace{\left(\boldsymbol{X}^T \boldsymbol{X}\right)^{-1} \boldsymbol{X}^T \mathbb{E}(\boldsymbol{\varepsilon})}_{=\ 0}
 & \Bigg\vert\ \mathbb{E}(\boldsymbol{\varepsilon}) = 0\\
&= \boldsymbol{\beta} & \Box
\end{align}


`equation` from bookdown book:

\begin{equation} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation} 
