on:
  push:
    branches: master

name: bookdown

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc

      - name: Cache Renv packages
        uses: actions/cache@v1
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Cache TinyTex
        uses: actions/cache@v1
        with:
          path: $HOME/Library/TinyTex
          key: tinytex-${{ hashFiles('$HOME/Library/TinyTeX/texmf.cnf') }}
          restore-keys: tinytex-

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Install tinytex
        uses: r-lib/actions/setup-tinytex@v1

      - name: Install system dependencies + fonts
        run: |
          brew install cairo
          brew cask install xquartz
          brew tap homebrew/cask-fonts
          brew cask install font-source-code-pro
          brew cask install font-source-sans-pro
          brew cask install font-source-serif-pro
          fc-cache -fv
          # fc-list|grep Source
          fc-match source

      - name: Build GitBook
        run: Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook", quiet = TRUE)'

      - name: Build PDF
        run: Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book", quiet = TRUE)'

      - name: Install npm
        uses: actions/setup-node@v1

      - name: Deploy to Netlify
        # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install netlify-cli -g
          netlify deploy --prod --dir _book
