on:
  push:
    branches: master
name: bookdown
env:
  RENV_PATHS_ROOT: ~/.local/share/renv

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      # - name: Cache TinyTex
      #   uses: actions/cache@v1
      #   with:
      #     path: $HOME/Library/TinyTex
      #     key: tinytex-${{ hashFiles('$HOME/Library/TinyTeX/texmf.cnf') }}
      #     restore-keys: tinytex-

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install tinytex
        uses: r-lib/actions/setup-tinytex@v1

      - name: Install system dependencies
        run: |
          brew install cairo
          brew cask install xquartz

      - name: Install fonts
        run: |
          brew tap homebrew/cask-fonts
          brew cask install font-roboto
          brew cask install font-roboto-condensed
          #     brew cask install font-source-code-pro
          #     brew cask install font-source-sans-pro
          #     brew cask install font-source-serif-pro
          #     echo Copy texlive-fontconfig.conf to ~/.fonts/conf
          #     # Apparently only helps XeLaTeX to find texlive fonts, not system fonts
          #     cp $(kpsewhich -var-value TEXMFSYSVAR)/fonts/conf/texlive-fontconfig.conf $HOME/.fonts.conf
          #     fc-cache -fv
          #     fc-list -f "%{family}\n" | sort -u
          #     echo running texhash
          #     texhash

      - name: Build GitBook
        run: Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook", quiet = TRUE)'

      - name: Build PDF
        run: Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book", quiet = TRUE)'

      # - name: Install npm
      #   uses: actions/setup-node@v1
      #
      # - name: Deploy to Netlify
      #   # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   run: |
      #     npm install netlify-cli -g
      #     netlify deploy --prod --dir _book
